version: '3'

services:
  web:
    build: . 
    restart: always
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db 
      DB_PORT: 3306
      DB_DATABASE: apply
      DB_USERNAME: forge
      DB_PASSWORD: 123456
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'apply'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'forge'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123456'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456789'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    command: --default-authentication-plugin=mysql_native_password

    volumes:
      - db_data:/var/lib/mysql

volumes:
     db_data: 
